// Auto-generated by docs integration - DO NOT EDIT
export const generatedRegistry = {
  'tutorial': {
    content: import.meta.glob('/docs/tutorial/**/*.{md,mdx}', { eager: true }),
    toc: import.meta.glob('/docs/tutorial/**/_toc.ts', { eager: true }),
  },
  'pancakes': {
    content: import.meta.glob('/docs/pancakes/**/*.{md,mdx}', { eager: true }),
    toc: import.meta.glob('/docs/pancakes/**/_toc.ts', { eager: true }),
  },
  'cocktails': {
    content: import.meta.glob('/docs/cocktails/**/*.{md,mdx}', { eager: true }),
    toc: import.meta.glob('/docs/cocktails/**/_toc.ts', { eager: true }),
  }
}
